// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: verify.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CSID int32

const (
	CSID_ID_Invalid      CSID = 0
	CSID_ID_Heartbeat    CSID = 1
	CSID_ID_HeartbeatRsp CSID = 2
	CSID_ID_CipherKeyNtf CSID = 3
	CSID_ID_EmitCheque   CSID = 4
)

// Enum value maps for CSID.
var (
	CSID_name = map[int32]string{
		0: "ID_Invalid",
		1: "ID_Heartbeat",
		2: "ID_HeartbeatRsp",
		3: "ID_CipherKeyNtf",
		4: "ID_EmitCheque",
	}
	CSID_value = map[string]int32{
		"ID_Invalid":      0,
		"ID_Heartbeat":    1,
		"ID_HeartbeatRsp": 2,
		"ID_CipherKeyNtf": 3,
		"ID_EmitCheque":   4,
	}
)

func (x CSID) Enum() *CSID {
	p := new(CSID)
	*p = x
	return p
}

func (x CSID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CSID) Descriptor() protoreflect.EnumDescriptor {
	return file_verify_proto_enumTypes[0].Descriptor()
}

func (CSID) Type() protoreflect.EnumType {
	return &file_verify_proto_enumTypes[0]
}

func (x CSID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CSID.Descriptor instead.
func (CSID) EnumDescriptor() ([]byte, []int) {
	return file_verify_proto_rawDescGZIP(), []int{0}
}

type Heartbeat struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Peer           string `protobuf:"bytes,1,opt,name=peer,proto3" json:"peer,omitempty"`
	EthAddr        string `protobuf:"bytes,2,opt,name=ethAddr,proto3" json:"ethAddr,omitempty"`
	ChequebookAddr string `protobuf:"bytes,3,opt,name=chequebookAddr,proto3" json:"chequebookAddr,omitempty"`
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verify_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_verify_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_verify_proto_rawDescGZIP(), []int{0}
}

func (x *Heartbeat) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

func (x *Heartbeat) GetEthAddr() string {
	if x != nil {
		return x.EthAddr
	}
	return ""
}

func (x *Heartbeat) GetChequebookAddr() string {
	if x != nil {
		return x.ChequebookAddr
	}
	return ""
}

type HeartbeatRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *HeartbeatRsp) Reset() {
	*x = HeartbeatRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verify_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRsp) ProtoMessage() {}

func (x *HeartbeatRsp) ProtoReflect() protoreflect.Message {
	mi := &file_verify_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRsp.ProtoReflect.Descriptor instead.
func (*HeartbeatRsp) Descriptor() ([]byte, []int) {
	return file_verify_proto_rawDescGZIP(), []int{1}
}

func (x *HeartbeatRsp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CipherKeyNtf struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SvrKey string `protobuf:"bytes,1,opt,name=svrKey,proto3" json:"svrKey,omitempty"`
	CltKey string `protobuf:"bytes,2,opt,name=cltKey,proto3" json:"cltKey,omitempty"`
}

func (x *CipherKeyNtf) Reset() {
	*x = CipherKeyNtf{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verify_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CipherKeyNtf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CipherKeyNtf) ProtoMessage() {}

func (x *CipherKeyNtf) ProtoReflect() protoreflect.Message {
	mi := &file_verify_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CipherKeyNtf.ProtoReflect.Descriptor instead.
func (*CipherKeyNtf) Descriptor() ([]byte, []int) {
	return file_verify_proto_rawDescGZIP(), []int{2}
}

func (x *CipherKeyNtf) GetSvrKey() string {
	if x != nil {
		return x.SvrKey
	}
	return ""
}

func (x *CipherKeyNtf) GetCltKey() string {
	if x != nil {
		return x.CltKey
	}
	return ""
}

type EmitCheque struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cheque []byte `protobuf:"bytes,1,opt,name=Cheque,proto3" json:"Cheque,omitempty"`
}

func (x *EmitCheque) Reset() {
	*x = EmitCheque{}
	if protoimpl.UnsafeEnabled {
		mi := &file_verify_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmitCheque) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmitCheque) ProtoMessage() {}

func (x *EmitCheque) ProtoReflect() protoreflect.Message {
	mi := &file_verify_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmitCheque.ProtoReflect.Descriptor instead.
func (*EmitCheque) Descriptor() ([]byte, []int) {
	return file_verify_proto_rawDescGZIP(), []int{3}
}

func (x *EmitCheque) GetCheque() []byte {
	if x != nil {
		return x.Cheque
	}
	return nil
}

var File_verify_proto protoreflect.FileDescriptor

var file_verify_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x61,
	0x0a, 0x09, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x65, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x65, 0x65, 0x72, 0x12,
	0x18, 0x0a, 0x07, 0x65, 0x74, 0x68, 0x41, 0x64, 0x64, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x65, 0x74, 0x68, 0x41, 0x64, 0x64, 0x72, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x68, 0x65,
	0x71, 0x75, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x41, 0x64, 0x64, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0e, 0x63, 0x68, 0x65, 0x71, 0x75, 0x65, 0x62, 0x6f, 0x6f, 0x6b, 0x41, 0x64, 0x64,
	0x72, 0x22, 0x20, 0x0a, 0x0c, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x73,
	0x70, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0x3e, 0x0a, 0x0c, 0x43, 0x69, 0x70, 0x68, 0x65, 0x72, 0x4b, 0x65, 0x79,
	0x4e, 0x74, 0x66, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x76, 0x72, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x76, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x63,
	0x6c, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6c, 0x74,
	0x4b, 0x65, 0x79, 0x22, 0x24, 0x0a, 0x0a, 0x45, 0x6d, 0x69, 0x74, 0x43, 0x68, 0x65, 0x71, 0x75,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x68, 0x65, 0x71, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x06, 0x43, 0x68, 0x65, 0x71, 0x75, 0x65, 0x2a, 0x65, 0x0a, 0x04, 0x43, 0x53, 0x49,
	0x44, 0x12, 0x0e, 0x0a, 0x0a, 0x49, 0x44, 0x5f, 0x49, 0x6e, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x10,
	0x00, 0x12, 0x10, 0x0a, 0x0c, 0x49, 0x44, 0x5f, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61,
	0x74, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x44, 0x5f, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62,
	0x65, 0x61, 0x74, 0x52, 0x73, 0x70, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x44, 0x5f, 0x43,
	0x69, 0x70, 0x68, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x4e, 0x74, 0x66, 0x10, 0x03, 0x12, 0x11, 0x0a,
	0x0d, 0x49, 0x44, 0x5f, 0x45, 0x6d, 0x69, 0x74, 0x43, 0x68, 0x65, 0x71, 0x75, 0x65, 0x10, 0x04,
	0x42, 0x18, 0x5a, 0x16, 0x2e, 0x2e, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x63,
	0x73, 0x2f, 0x3b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_verify_proto_rawDescOnce sync.Once
	file_verify_proto_rawDescData = file_verify_proto_rawDesc
)

func file_verify_proto_rawDescGZIP() []byte {
	file_verify_proto_rawDescOnce.Do(func() {
		file_verify_proto_rawDescData = protoimpl.X.CompressGZIP(file_verify_proto_rawDescData)
	})
	return file_verify_proto_rawDescData
}

var file_verify_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_verify_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_verify_proto_goTypes = []interface{}{
	(CSID)(0),            // 0: CSID
	(*Heartbeat)(nil),    // 1: Heartbeat
	(*HeartbeatRsp)(nil), // 2: HeartbeatRsp
	(*CipherKeyNtf)(nil), // 3: CipherKeyNtf
	(*EmitCheque)(nil),   // 4: EmitCheque
}
var file_verify_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_verify_proto_init() }
func file_verify_proto_init() {
	if File_verify_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_verify_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Heartbeat); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_verify_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_verify_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CipherKeyNtf); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_verify_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmitCheque); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_verify_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_verify_proto_goTypes,
		DependencyIndexes: file_verify_proto_depIdxs,
		EnumInfos:         file_verify_proto_enumTypes,
		MessageInfos:      file_verify_proto_msgTypes,
	}.Build()
	File_verify_proto = out.File
	file_verify_proto_rawDesc = nil
	file_verify_proto_goTypes = nil
	file_verify_proto_depIdxs = nil
}
